# Generated by Django 3.2.4 on 2021-07-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Floo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='team',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='title',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('description', models.CharField(blank=True, max_length=2055, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Floo.team')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='Floo.topic'),
        ),
    ]
