# Generated by Django 3.2.4 on 2021-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Floo', '0003_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
