# Generated by Django 3.2.4 on 2021-06-27 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Floo', '0005_alter_meeting_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
