version: '3.8'

services:
  db:
    restart: always
    build: postgres
    container_name: floo_db
    env_file:
      - postgres/database.env
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data/
    networks: 
      - floo_network
  
  redis:
    restart: always
    build: redis
    container_name: floo_redis
    expose:
      - 6379
    networks: 
      - floo_network
  
  backend:
    restart: always
    build:
      context: backend
    container_name: floo_backend
    command: sh -c "python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/code/:/code/
      - ./static/:/static/
      - ./media/:/media/
    expose:
      - 8000
    ports:
      - "54321:8000"
    depends_on: 
      - db
      - redis
    networks: 
      - floo_network

volumes:
  database:


networks: 
  floo_network:
