version: '3.8'

services:
  db:
    build: ../postgres
    restart: always
    container_name: floo_postgres
    expose:
      - 5432
    
    user: postgres
    env_file:
      - ../postgres/database.env

    volumes:
      - type: volume
        source: database
        target: /var/lib/postgres/data/
        read_only: false
    
    networks:
      - floo_network
  

  redis:
    build: ../redis
    restart: always
    container_name: floo_redis
    expose:
      - 6379

    user: redis

    networks:
      - floo_network
  
  
  backend:
    build:
      context: ../backend
    restart: always
    container_name: floo_backend
    expose:
      - 8000
      - 8001
    
    # user: django

    command: sh -c "python manage.py collectstatic --no-input && supervisord -c /supervisord.conf"

    volumes:
      - ../backend/code/:/code
      - ../static/:/static/
      - ../media/:/media/
      - server_logs:/server_logs/
    
    depends_on:
      - db
      - redis
    
    networks:
      - floo_network
    

  reverse_proxy:
    build:
      context: ../nginx
    restart: always
    container_name: floo_reverse_proxy

    expose:
      - 80
    ports:
      - "54321:80"
    
    volumes:
      - ../static/:/static/
      - ../media/:/media/
      - reverse_proxy_logs:/reverse_proxy_logs/
      
    depends_on:
      - backend
    
    networks:
      - floo_network


volumes:
  database:

  server_logs:
  reverse_logs:
  
  reverse_proxy_logs:
  
networks:
  floo_network:
