version: '3.8'

services:
  db:
    build: ../postgres
    restart: always
    container_name: floo_db

    user: postgres

    env_file:
      - ../postgres/database.env

    expose:
      - 5432    

    volumes:
      - type: volume
        source: database
        target: /var/lib/postgres/data/
        read_only: false
    
    networks:
      - floo_network
  

  redis:
    build: ../redis
    restart: always
    container_name: floo_redis

    user: redis

    expose:
      - 6379

    networks:
      - floo_network
  
  
  backend:
    build:
      context: ../backend
    restart: always
    container_name: floo_backend

    user: django
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && supervisord -c /supervisord.conf"

    expose:
      - 8000
      - 8001

    volumes:
      - type: bind
        source: ../backend/code/
        target: /code/
        read_only: true

      - type: volume
        source: static
        target: /static/
        read_only: false
      
      - type: volume
        source: media
        target: /media/
        read_only: false
      
      - type: volume
        source: server_logs
        target: /server_logs/
        read_only: false
    
    depends_on:
      - db
      - redis
    
    networks:
      - floo_network
    

  reverse_proxy:
    build:
      context: ../nginx
    restart: always
    container_name: floo_reverse_proxy

    expose:
      - 80
    ports:
      - "54321:80"
    
    volumes:
      - type: volume
        source: static
        target: /static/
        read_only: true
      
      - type: volume
        source: media
        target: /media/
        read_only: true
      
      - type: volume
        source: reverse_proxy_logs
        target: /reverse_proxy_logs/
        read_only: false

      
    depends_on:
      - backend
    
    networks:
      - floo_network


volumes:
  database:

  static:
  media:
  server_logs:

  reverse_proxy_logs:


networks:
  floo_network:
