DEBUG: FALSE
SECRET_KEY: # SECRET KEY

# Database configuration
DATABASE:
  NAME: # Database name
  USER: # User who has access to the database
  PASSWORD: # Password of the user
  HOST: "db" # URL / IP of the database server
  PORT: 5432 # Port on which the server is listening

CHANNEL_LAYER:
  HOST: "redis" # URL / IP of the redis server
  PORT: 6379 # Port on which the server is listening

ALLOWED_HOSTS:
  - "localhost"
  - "127.0.0.1"
  - "db"

CORS_ALLOWED_ORIGINS:
  - "http://localhost:3000"

# Directory in which the static files will be stored
STATIC_ROOT: "../floo_static/"

# Directory in which the media files will be stored
MEDIA_ROOT: "../floo_media/"

# Google OAuth
GOOGLE_OAUTH:
  CLIENT_ID: # Google Client ID
  CLIENT_SECRET: # Client Secret
